Fix missing dependency
Fixes the following error during Dockerfile build:

    [2/2] STEP 9/14: RUN /app/entrypoint.sh python -c 'import resultsdb'     && mod_wsgi-express module-config     && /app/entrypoint.sh resultsdb --help
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
        import resultsdb
    File "/venv/lib64/python3.13/site-packages/resultsdb/__init__.py", line 38, in <module>
        from resultsdb.controllers.api_v2 import api as api_v2
    File "/venv/lib64/python3.13/site-packages/resultsdb/controllers/api_v2.py", line 30, in <module>
        from resultsdb.controllers.common import SERIALIZE, commit_result
    File "/venv/lib64/python3.13/site-packages/resultsdb/controllers/common.py", line 5, in <module>
        from resultsdb.messaging import create_message, publish_taskotron_message
    File "/venv/lib64/python3.13/site-packages/resultsdb/messaging.py", line 25, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'

JIRA: RHELWF-13625